
import os
import numpy as np
import json 
from gurobipy import Model, GRB, quicksum


model = Model("OptimizationProblem")

with open("data.json", "r") as f:
    data = json.load(f)




### Define the parameters

OriginalFoodWaste = data["OriginalFoodWaste"] # shape: [], definition: Food waste generated by the original meal

OriginalWrappingWaste = data["OriginalWrappingWaste"] # shape: [], definition: Wrapping waste generated by the original meal

OriginalCookingTime = data["OriginalCookingTime"] # shape: [], definition: Cooking time for the original meal

ExperimentalFoodWaste = data["ExperimentalFoodWaste"] # shape: [], definition: Food waste generated by the experimental meal

ExperimentalWrappingWaste = data["ExperimentalWrappingWaste"] # shape: [], definition: Wrapping waste generated by the experimental meal

ExperimentalCookingTime = data["ExperimentalCookingTime"] # shape: [], definition: Cooking time for the experimental meal

MaxWrappingWaste = data["MaxWrappingWaste"] # shape: [], definition: Maximum allowed wrapping waste

MaxFoodWaste = data["MaxFoodWaste"] # shape: [], definition: Maximum allowed food waste



### Define the variables

OriginalMeals = model.addVar(vtype=GRB.INTEGER, name="OriginalMeals")

ExperimentalMeals = model.addVar(vtype=GRB.INTEGER, name="ExperimentalMeals")



### Define the constraints

model.addConstr(45 * OriginalMeals + 35 * ExperimentalMeals <= MaxWrappingWaste)
model.addConstr(OriginalMeals >= 0)
model.addConstr(ExperimentalMeals >= 0)



### Define the objective

model.setObjective(OriginalCookingTime * OriginalMeals + ExperimentalCookingTime * ExperimentalMeals, GRB.MINIMIZE)


### Optimize the model

model.optimize()



### Output optimal objective value

print("Optimal Objective Value: ", model.objVal)


if model.status == GRB.OPTIMAL:
    with open("output_solution.txt", "w") as f:
        f.write(str(model.objVal))
    print("Optimal Objective Value: ", model.objVal)
else:
    with open("output_solution.txt", "w") as f:
        f.write(model.status)
